[profile.default]
src = 'contracts'
out = 'out/foundry'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache/foundry'
gas_reports = ["*"]
script = 'script'
solc_version = '0.8.25'
optimizer = true
optimizer_runs = 200